
language: python
python:
  - "3.7"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
  packages:
    - gcc-7
    - g++-7

notifications:
  email: false

install:
    - pip install -q cython
    - export CFLAGS='-std=c++11'
    - python setup.py build_ext --inplace

script:
  - pytest cpp_faster_fifo/tests/test_faster_fifo.py