language: python
matrix:
  include:
    - os: linux
      dist: bionic
      python:
        - "3.6"
        - "3.7"
        - "3.8"
      install:
        - pip install faster-fifo

    - os: osx
      osx_image: xcode11.2
      language: shell
      before_install:
        - export CC=gcc-9
        - export CXX=g++-9
      install:
        - python3 setup.py build_ext --inplace

notifications:
  email: false

before_install:
  - pip3 install -q cython
  - pip3 install coverage

script:
  - coverage run -m unittest cpp_faster_fifo/tests/test_faster_fifo.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
