
language: python
dist: bionic
python:
  - "3.5"
  - "3.6"
  - "3.7"

notifications:
  email: false

install:
    - pip install -q cython
    - pip install coverage
    - pip install faster-fifo

script:
  - coverage run -m unittest cpp_faster_fifo/tests/test_faster_fifo.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
