
language: python
python:
  - "3.7"
include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-4.8']
    env: COMPILER=g++-4.8

notifications:
  email: false

install:
    - pip install -q cython
    - python setup.py build_ext --inplace

script:
  - pytest cpp_faster_fifo/tests/test_faster_fifo.py